// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"zero/rpc/dao/model"
)

func newAutoMessage(db *gorm.DB, opts ...gen.DOOption) autoMessage {
	_autoMessage := autoMessage{}

	_autoMessage.autoMessageDo.UseDB(db, opts...)
	_autoMessage.autoMessageDo.UseModel(&model.AutoMessage{})

	tableName := _autoMessage.autoMessageDo.TableName()
	_autoMessage.ALL = field.NewAsterisk(tableName)
	_autoMessage.ID = field.NewInt64(tableName, "id")
	_autoMessage.Name = field.NewString(tableName, "name")
	_autoMessage.Type = field.NewString(tableName, "type")
	_autoMessage.Content = field.NewString(tableName, "content")
	_autoMessage.GroupID = field.NewInt64(tableName, "group_id")
	_autoMessage.CreatedAt = field.NewTime(tableName, "created_at")
	_autoMessage.UpdatedAt = field.NewTime(tableName, "updated_at")

	_autoMessage.fillFieldMap()

	return _autoMessage
}

type autoMessage struct {
	autoMessageDo autoMessageDo

	ALL       field.Asterisk
	ID        field.Int64
	Name      field.String
	Type      field.String
	Content   field.String
	GroupID   field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (a autoMessage) Table(newTableName string) *autoMessage {
	a.autoMessageDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a autoMessage) As(alias string) *autoMessage {
	a.autoMessageDo.DO = *(a.autoMessageDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *autoMessage) updateTableName(table string) *autoMessage {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Name = field.NewString(table, "name")
	a.Type = field.NewString(table, "type")
	a.Content = field.NewString(table, "content")
	a.GroupID = field.NewInt64(table, "group_id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *autoMessage) WithContext(ctx context.Context) *autoMessageDo {
	return a.autoMessageDo.WithContext(ctx)
}

func (a autoMessage) TableName() string { return a.autoMessageDo.TableName() }

func (a autoMessage) Alias() string { return a.autoMessageDo.Alias() }

func (a autoMessage) Columns(cols ...field.Expr) gen.Columns { return a.autoMessageDo.Columns(cols...) }

func (a *autoMessage) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *autoMessage) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["name"] = a.Name
	a.fieldMap["type"] = a.Type
	a.fieldMap["content"] = a.Content
	a.fieldMap["group_id"] = a.GroupID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a autoMessage) clone(db *gorm.DB) autoMessage {
	a.autoMessageDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a autoMessage) replaceDB(db *gorm.DB) autoMessage {
	a.autoMessageDo.ReplaceDB(db)
	return a
}

type autoMessageDo struct{ gen.DO }

func (a autoMessageDo) Debug() *autoMessageDo {
	return a.withDO(a.DO.Debug())
}

func (a autoMessageDo) WithContext(ctx context.Context) *autoMessageDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a autoMessageDo) ReadDB() *autoMessageDo {
	return a.Clauses(dbresolver.Read)
}

func (a autoMessageDo) WriteDB() *autoMessageDo {
	return a.Clauses(dbresolver.Write)
}

func (a autoMessageDo) Session(config *gorm.Session) *autoMessageDo {
	return a.withDO(a.DO.Session(config))
}

func (a autoMessageDo) Clauses(conds ...clause.Expression) *autoMessageDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a autoMessageDo) Returning(value interface{}, columns ...string) *autoMessageDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a autoMessageDo) Not(conds ...gen.Condition) *autoMessageDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a autoMessageDo) Or(conds ...gen.Condition) *autoMessageDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a autoMessageDo) Select(conds ...field.Expr) *autoMessageDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a autoMessageDo) Where(conds ...gen.Condition) *autoMessageDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a autoMessageDo) Order(conds ...field.Expr) *autoMessageDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a autoMessageDo) Distinct(cols ...field.Expr) *autoMessageDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a autoMessageDo) Omit(cols ...field.Expr) *autoMessageDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a autoMessageDo) Join(table schema.Tabler, on ...field.Expr) *autoMessageDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a autoMessageDo) LeftJoin(table schema.Tabler, on ...field.Expr) *autoMessageDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a autoMessageDo) RightJoin(table schema.Tabler, on ...field.Expr) *autoMessageDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a autoMessageDo) Group(cols ...field.Expr) *autoMessageDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a autoMessageDo) Having(conds ...gen.Condition) *autoMessageDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a autoMessageDo) Limit(limit int) *autoMessageDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a autoMessageDo) Offset(offset int) *autoMessageDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a autoMessageDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *autoMessageDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a autoMessageDo) Unscoped() *autoMessageDo {
	return a.withDO(a.DO.Unscoped())
}

func (a autoMessageDo) Create(values ...*model.AutoMessage) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a autoMessageDo) CreateInBatches(values []*model.AutoMessage, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a autoMessageDo) Save(values ...*model.AutoMessage) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a autoMessageDo) First() (*model.AutoMessage, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AutoMessage), nil
	}
}

func (a autoMessageDo) Take() (*model.AutoMessage, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AutoMessage), nil
	}
}

func (a autoMessageDo) Last() (*model.AutoMessage, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AutoMessage), nil
	}
}

func (a autoMessageDo) Find() ([]*model.AutoMessage, error) {
	result, err := a.DO.Find()
	return result.([]*model.AutoMessage), err
}

func (a autoMessageDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AutoMessage, err error) {
	buf := make([]*model.AutoMessage, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a autoMessageDo) FindInBatches(result *[]*model.AutoMessage, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a autoMessageDo) Attrs(attrs ...field.AssignExpr) *autoMessageDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a autoMessageDo) Assign(attrs ...field.AssignExpr) *autoMessageDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a autoMessageDo) Joins(fields ...field.RelationField) *autoMessageDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a autoMessageDo) Preload(fields ...field.RelationField) *autoMessageDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a autoMessageDo) FirstOrInit() (*model.AutoMessage, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AutoMessage), nil
	}
}

func (a autoMessageDo) FirstOrCreate() (*model.AutoMessage, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AutoMessage), nil
	}
}

func (a autoMessageDo) FindByPage(offset int, limit int) (result []*model.AutoMessage, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a autoMessageDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a autoMessageDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a autoMessageDo) Delete(models ...*model.AutoMessage) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *autoMessageDo) withDO(do gen.Dao) *autoMessageDo {
	a.DO = *do.(*gen.DO)
	return a
}
