// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"zero/rpc/dao/model"
)

func newAutoRuleScene(db *gorm.DB, opts ...gen.DOOption) autoRuleScene {
	_autoRuleScene := autoRuleScene{}

	_autoRuleScene.autoRuleSceneDo.UseDB(db, opts...)
	_autoRuleScene.autoRuleSceneDo.UseModel(&model.AutoRuleScene{})

	tableName := _autoRuleScene.autoRuleSceneDo.TableName()
	_autoRuleScene.ALL = field.NewAsterisk(tableName)
	_autoRuleScene.ID = field.NewInt64(tableName, "id")
	_autoRuleScene.Name = field.NewString(tableName, "name")
	_autoRuleScene.RuleID = field.NewInt64(tableName, "rule_id")
	_autoRuleScene.CreatedAt = field.NewTime(tableName, "created_at")
	_autoRuleScene.UpdatedAt = field.NewTime(tableName, "updated_at")

	_autoRuleScene.fillFieldMap()

	return _autoRuleScene
}

type autoRuleScene struct {
	autoRuleSceneDo autoRuleSceneDo

	ALL       field.Asterisk
	ID        field.Int64
	Name      field.String
	RuleID    field.Int64
	CreatedAt field.Time
	UpdatedAt field.Time

	fieldMap map[string]field.Expr
}

func (a autoRuleScene) Table(newTableName string) *autoRuleScene {
	a.autoRuleSceneDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a autoRuleScene) As(alias string) *autoRuleScene {
	a.autoRuleSceneDo.DO = *(a.autoRuleSceneDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *autoRuleScene) updateTableName(table string) *autoRuleScene {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt64(table, "id")
	a.Name = field.NewString(table, "name")
	a.RuleID = field.NewInt64(table, "rule_id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")

	a.fillFieldMap()

	return a
}

func (a *autoRuleScene) WithContext(ctx context.Context) *autoRuleSceneDo {
	return a.autoRuleSceneDo.WithContext(ctx)
}

func (a autoRuleScene) TableName() string { return a.autoRuleSceneDo.TableName() }

func (a autoRuleScene) Alias() string { return a.autoRuleSceneDo.Alias() }

func (a autoRuleScene) Columns(cols ...field.Expr) gen.Columns {
	return a.autoRuleSceneDo.Columns(cols...)
}

func (a *autoRuleScene) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *autoRuleScene) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 5)
	a.fieldMap["id"] = a.ID
	a.fieldMap["name"] = a.Name
	a.fieldMap["rule_id"] = a.RuleID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
}

func (a autoRuleScene) clone(db *gorm.DB) autoRuleScene {
	a.autoRuleSceneDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a autoRuleScene) replaceDB(db *gorm.DB) autoRuleScene {
	a.autoRuleSceneDo.ReplaceDB(db)
	return a
}

type autoRuleSceneDo struct{ gen.DO }

func (a autoRuleSceneDo) Debug() *autoRuleSceneDo {
	return a.withDO(a.DO.Debug())
}

func (a autoRuleSceneDo) WithContext(ctx context.Context) *autoRuleSceneDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a autoRuleSceneDo) ReadDB() *autoRuleSceneDo {
	return a.Clauses(dbresolver.Read)
}

func (a autoRuleSceneDo) WriteDB() *autoRuleSceneDo {
	return a.Clauses(dbresolver.Write)
}

func (a autoRuleSceneDo) Session(config *gorm.Session) *autoRuleSceneDo {
	return a.withDO(a.DO.Session(config))
}

func (a autoRuleSceneDo) Clauses(conds ...clause.Expression) *autoRuleSceneDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a autoRuleSceneDo) Returning(value interface{}, columns ...string) *autoRuleSceneDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a autoRuleSceneDo) Not(conds ...gen.Condition) *autoRuleSceneDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a autoRuleSceneDo) Or(conds ...gen.Condition) *autoRuleSceneDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a autoRuleSceneDo) Select(conds ...field.Expr) *autoRuleSceneDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a autoRuleSceneDo) Where(conds ...gen.Condition) *autoRuleSceneDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a autoRuleSceneDo) Order(conds ...field.Expr) *autoRuleSceneDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a autoRuleSceneDo) Distinct(cols ...field.Expr) *autoRuleSceneDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a autoRuleSceneDo) Omit(cols ...field.Expr) *autoRuleSceneDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a autoRuleSceneDo) Join(table schema.Tabler, on ...field.Expr) *autoRuleSceneDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a autoRuleSceneDo) LeftJoin(table schema.Tabler, on ...field.Expr) *autoRuleSceneDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a autoRuleSceneDo) RightJoin(table schema.Tabler, on ...field.Expr) *autoRuleSceneDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a autoRuleSceneDo) Group(cols ...field.Expr) *autoRuleSceneDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a autoRuleSceneDo) Having(conds ...gen.Condition) *autoRuleSceneDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a autoRuleSceneDo) Limit(limit int) *autoRuleSceneDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a autoRuleSceneDo) Offset(offset int) *autoRuleSceneDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a autoRuleSceneDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *autoRuleSceneDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a autoRuleSceneDo) Unscoped() *autoRuleSceneDo {
	return a.withDO(a.DO.Unscoped())
}

func (a autoRuleSceneDo) Create(values ...*model.AutoRuleScene) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a autoRuleSceneDo) CreateInBatches(values []*model.AutoRuleScene, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a autoRuleSceneDo) Save(values ...*model.AutoRuleScene) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a autoRuleSceneDo) First() (*model.AutoRuleScene, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.AutoRuleScene), nil
	}
}

func (a autoRuleSceneDo) Take() (*model.AutoRuleScene, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.AutoRuleScene), nil
	}
}

func (a autoRuleSceneDo) Last() (*model.AutoRuleScene, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.AutoRuleScene), nil
	}
}

func (a autoRuleSceneDo) Find() ([]*model.AutoRuleScene, error) {
	result, err := a.DO.Find()
	return result.([]*model.AutoRuleScene), err
}

func (a autoRuleSceneDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.AutoRuleScene, err error) {
	buf := make([]*model.AutoRuleScene, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a autoRuleSceneDo) FindInBatches(result *[]*model.AutoRuleScene, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a autoRuleSceneDo) Attrs(attrs ...field.AssignExpr) *autoRuleSceneDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a autoRuleSceneDo) Assign(attrs ...field.AssignExpr) *autoRuleSceneDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a autoRuleSceneDo) Joins(fields ...field.RelationField) *autoRuleSceneDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a autoRuleSceneDo) Preload(fields ...field.RelationField) *autoRuleSceneDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a autoRuleSceneDo) FirstOrInit() (*model.AutoRuleScene, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.AutoRuleScene), nil
	}
}

func (a autoRuleSceneDo) FirstOrCreate() (*model.AutoRuleScene, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.AutoRuleScene), nil
	}
}

func (a autoRuleSceneDo) FindByPage(offset int, limit int) (result []*model.AutoRuleScene, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a autoRuleSceneDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a autoRuleSceneDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a autoRuleSceneDo) Delete(models ...*model.AutoRuleScene) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *autoRuleSceneDo) withDO(do gen.Dao) *autoRuleSceneDo {
	a.DO = *do.(*gen.DO)
	return a
}
