// Code generated by goctl. DO NOT EDIT.
// Source: zero.proto

package server

import (
	"context"

	"zero/rpc/internal/logic"
	"zero/rpc/internal/svc"
	"zero/rpc/zero"
)

type ZeroServer struct {
	svcCtx *svc.ServiceContext
	zero.UnimplementedZeroServer
}

func NewZeroServer(svcCtx *svc.ServiceContext) *ZeroServer {
	return &ZeroServer{
		svcCtx: svcCtx,
	}
}

// Base service
func (s *ZeroServer) Ping(ctx context.Context, in *zero.Request) (*zero.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *ZeroServer) InitDatabase(ctx context.Context, in *zero.Empty) (*zero.BaseResp, error) {
	l := logic.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}

// Admin service
func (s *ZeroServer) AdminList(ctx context.Context, in *zero.AdminListReq) (*zero.AdminListResp, error) {
	l := logic.NewAdminListLogic(ctx, s.svcCtx)
	return l.AdminList(in)
}

func (s *ZeroServer) AdminCreate(ctx context.Context, in *zero.AdminInfo) (*zero.BaseIDResp, error) {
	l := logic.NewAdminCreateLogic(ctx, s.svcCtx)
	return l.AdminCreate(in)
}

func (s *ZeroServer) AdminUpdate(ctx context.Context, in *zero.AdminInfo) (*zero.BaseResp, error) {
	l := logic.NewAdminUpdateLogic(ctx, s.svcCtx)
	return l.AdminUpdate(in)
}

func (s *ZeroServer) AdminDelete(ctx context.Context, in *zero.AdminInfo) (*zero.BaseResp, error) {
	l := logic.NewAdminDeleteLogic(ctx, s.svcCtx)
	return l.AdminDelete(in)
}

func (s *ZeroServer) AdminDetail(ctx context.Context, in *zero.IDReq) (*zero.AdminInfo, error) {
	l := logic.NewAdminDetailLogic(ctx, s.svcCtx)
	return l.AdminDetail(in)
}
