// Code generated by goctl. DO NOT EDIT.
package types

type Admin struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Avatar   string `json:"avatar"`
}

type BaseResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,omitempty"`
}

type IDReq struct {
	ID int `json:"id"`
}

type IDsReq struct {
	IDs []int `json:"ids"`
}

type IndexReq struct {
	Username string `json:"username"`
	PageReq
}

type IndexResp struct {
	ListResp
	Data []Admin `json:"data"`
}

type ListResp struct {
	Total int         `json:"total"`
	Data  interface{} `json:"data,omitempty"`
}

type LoginInfo struct {
	Id       int64  `json:"id"`
	Username string `json:"username"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	BaseResp
	Data LoginInfo `json:"data"`
}

type PageReq struct {
	Page int `json:"page"`
	Size int `json:"size"`
}

type ShowResp struct {
	BaseResp
	Data Admin `json:"data"`
}
