// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	admin "zero/api/internal/handler/admin"
	"zero/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/login",
				Handler: admin.LoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/admin",
				Handler: admin.IndexHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/:id",
				Handler: admin.ShowHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)
}
