// Code generated by goctl. DO NOT EDIT.
// Source: zero.proto

package zeroclient

import (
	"context"

	"zero/rpc/zero"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AdminInfo     = zero.AdminInfo
	AdminListReq  = zero.AdminListReq
	AdminListResp = zero.AdminListResp
	BaseIDResp    = zero.BaseIDResp
	BaseResp      = zero.BaseResp
	Empty         = zero.Empty
	IDReq         = zero.IDReq
	IDsReq        = zero.IDsReq
	PageReq       = zero.PageReq
	PageResp      = zero.PageResp
	Request       = zero.Request
	Response      = zero.Response

	Zero interface {
		// Base service
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error)
		// Admin service
		AdminList(ctx context.Context, in *AdminListReq, opts ...grpc.CallOption) (*AdminListResp, error)
		AdminCreate(ctx context.Context, in *AdminInfo, opts ...grpc.CallOption) (*BaseIDResp, error)
		AdminUpdate(ctx context.Context, in *AdminInfo, opts ...grpc.CallOption) (*BaseResp, error)
		AdminDelete(ctx context.Context, in *AdminInfo, opts ...grpc.CallOption) (*BaseResp, error)
		AdminDetail(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*AdminInfo, error)
	}

	defaultZero struct {
		cli zrpc.Client
	}
)

func NewZero(cli zrpc.Client) Zero {
	return &defaultZero{
		cli: cli,
	}
}

// Base service
func (m *defaultZero) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := zero.NewZeroClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultZero) InitDatabase(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*BaseResp, error) {
	client := zero.NewZeroClient(m.cli.Conn())
	return client.InitDatabase(ctx, in, opts...)
}

// Admin service
func (m *defaultZero) AdminList(ctx context.Context, in *AdminListReq, opts ...grpc.CallOption) (*AdminListResp, error) {
	client := zero.NewZeroClient(m.cli.Conn())
	return client.AdminList(ctx, in, opts...)
}

func (m *defaultZero) AdminCreate(ctx context.Context, in *AdminInfo, opts ...grpc.CallOption) (*BaseIDResp, error) {
	client := zero.NewZeroClient(m.cli.Conn())
	return client.AdminCreate(ctx, in, opts...)
}

func (m *defaultZero) AdminUpdate(ctx context.Context, in *AdminInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	client := zero.NewZeroClient(m.cli.Conn())
	return client.AdminUpdate(ctx, in, opts...)
}

func (m *defaultZero) AdminDelete(ctx context.Context, in *AdminInfo, opts ...grpc.CallOption) (*BaseResp, error) {
	client := zero.NewZeroClient(m.cli.Conn())
	return client.AdminDelete(ctx, in, opts...)
}

func (m *defaultZero) AdminDetail(ctx context.Context, in *IDReq, opts ...grpc.CallOption) (*AdminInfo, error) {
	client := zero.NewZeroClient(m.cli.Conn())
	return client.AdminDetail(ctx, in, opts...)
}
