// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAdmin = "admins"

// Admin mapped from table <admins>
type Admin struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Username  string         `gorm:"column:username" json:"username"`
	Password  string         `gorm:"column:password" json:"password"`
	APIToken  string         `gorm:"column:api_token" json:"api_token"`
	Avatar    string         `gorm:"column:avatar" json:"avatar"`
	GroupID   int64          `gorm:"column:group_id" json:"group_id"`
	IsSuper   bool           `gorm:"column:is_super" json:"is_super"`
}

// TableName Admin's table name
func (*Admin) TableName() string {
	return TableNameAdmin
}
