// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAdminChatSetting = "admin_chat_settings"

// AdminChatSetting mapped from table <admin_chat_settings>
type AdminChatSetting struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AdminID        int64     `gorm:"column:admin_id" json:"admin_id"`
	Background     string    `gorm:"column:background" json:"background"`
	IsAutoAccept   bool      `gorm:"column:is_auto_accept" json:"is_auto_accept"`
	WelcomeContent string    `gorm:"column:welcome_content" json:"welcome_content"`
	OfflineContent string    `gorm:"column:offline_content" json:"offline_content"`
	Name           string    `gorm:"column:name" json:"name"`
	LastOnline     time.Time `gorm:"column:last_online" json:"last_online"`
	Avatar         string    `gorm:"column:avatar" json:"avatar"`
	CreatedAt      time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName AdminChatSetting's table name
func (*AdminChatSetting) TableName() string {
	return TableNameAdminChatSetting
}
