// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAutoRuleScene = "auto_rule_scenes"

// AutoRuleScene mapped from table <auto_rule_scenes>
type AutoRuleScene struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name" json:"name"`
	RuleID    int64     `gorm:"column:rule_id" json:"rule_id"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName AutoRuleScene's table name
func (*AutoRuleScene) TableName() string {
	return TableNameAutoRuleScene
}
