// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAutoRule = "auto_rules"

// AutoRule mapped from table <auto_rules>
type AutoRule struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name" json:"name"`
	Match     string    `gorm:"column:match" json:"match"`
	MatchType string    `gorm:"column:match_type" json:"match_type"`
	ReplyType string    `gorm:"column:reply_type" json:"reply_type"`
	MessageID int64     `gorm:"column:message_id" json:"message_id"`
	Key       string    `gorm:"column:key" json:"key"`
	IsSystem  int32     `gorm:"column:is_system" json:"is_system"`
	Sort      int32     `gorm:"column:sort" json:"sort"`
	IsOpen    bool      `gorm:"column:is_open" json:"is_open"`
	GroupID   int64     `gorm:"column:group_id" json:"group_id"`
	Count     int64     `gorm:"column:count;not null" json:"count"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName AutoRule's table name
func (*AutoRule) TableName() string {
	return TableNameAutoRule
}
