// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameChatTransfer = "chat_transfers"

// ChatTransfer mapped from table <chat_transfers>
type ChatTransfer struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID      int64  `gorm:"column:user_id" json:"user_id"`
	SessionID   int64  `gorm:"column:session_id" json:"session_id"`
	FromAdminID int64  `gorm:"column:from_admin_id" json:"from_admin_id"`
	ToAdminID   int64  `gorm:"column:to_admin_id" json:"to_admin_id"`
	GroupID     int64  `gorm:"column:group_id" json:"group_id"`
	Remark      string `gorm:"column:remark" json:"remark"`
	IsAccepted  bool   `gorm:"column:is_accepted" json:"is_accepted"`
	IsCanceled  bool   `gorm:"column:is_canceled" json:"is_canceled"`
	CreatedAt   int64  `gorm:"column:created_at" json:"created_at"`
	AcceptedAt  int64  `gorm:"column:accepted_at" json:"accepted_at"`
	CanceledAt  int64  `gorm:"column:canceled_at" json:"canceled_at"`
}

// TableName ChatTransfer's table name
func (*ChatTransfer) TableName() string {
	return TableNameChatTransfer
}
