// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatSetting = "chat_settings"

// ChatSetting mapped from table <chat_settings>
type ChatSetting struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name      string    `gorm:"column:name" json:"name"`
	Title     string    `gorm:"column:title" json:"title"`
	GroupID   int64     `gorm:"column:group_id" json:"group_id"`
	Value     string    `gorm:"column:value" json:"value"`
	Options   string    `gorm:"column:options" json:"options"`
	Type      string    `gorm:"column:type" json:"type"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName ChatSetting's table name
func (*ChatSetting) TableName() string {
	return TableNameChatSetting
}
