// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMessage = "messages"

// Message mapped from table <messages>
type Message struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID     int64  `gorm:"column:user_id" json:"user_id"`
	AdminID    int64  `gorm:"column:admin_id" json:"admin_id"`
	Type       string `gorm:"column:type" json:"type"`
	Content    string `gorm:"column:content" json:"content"`
	ReceivedAt int64  `gorm:"column:received_at" json:"received_at"`
	GroupID    int64  `gorm:"column:group_id" json:"group_id"`
	SendAt     int64  `gorm:"column:send_at" json:"send_at"`
	Source     int32  `gorm:"column:source" json:"source"`
	SessionID  int64  `gorm:"column:session_id" json:"session_id"`
	ReqID      string `gorm:"column:req_id" json:"req_id"`
	IsRead     bool   `gorm:"column:is_read" json:"is_read"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
